// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfekwzfeoctfwoeujzkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmZWt3emZlb2N0ZndvZXVqemtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTE4NzQsImV4cCI6MjA2MTY2Nzg3NH0.ZT9BwexwwiMh71PMtdqO4nxIr3Zhp0kMSB6gYlFBHao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);